module.exports = {
  semi: true,
  trailingComma: 'es5',
  singleQuote: true,
  printWidth: 100,
  tabWidth: 2,
  endOfLine: 'lf',
  arrowParens: 'always',
  bracketSpacing: true,
  jsxBracketSameLine: false,
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-organize-imports'],
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(next/(.*)$)|^(next$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^@/components/(.*)$',
    '^@/hooks/(.*)$',
    '^@/models/(.*)$',
    '^@/routes/(.*)$',
    '^@/services/(.*)$',
    '^@/theme/(.*)$',
    '^@/utils/(.*)$',
    '^@/assets/(.*)$',
    '',
    '^[./]',
  ],
  importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
  importOrderTypeScriptVersion: '5.0.0',
};
