# Report Service - Expense Tracker

up:
	docker-compose up -d

up-build:
	docker-compose up -d --build

down:
	docker-compose down

logs:
	docker-compose logs -f report-service

install:
	npm install

dev:
	npm run start:dev

build:
	npm run build
