import {
  INotaFiscalCreateUpdate,
  INotaFiscalDestinatario,
  INotaFiscalEmitente,
  INotaFiscalExibicaoGeral,
  INotaFiscalLogistica,
  INotaFiscalMercadorias,
  INotaFiscalPagamentos,
  INotaFiscalProcesso,
  INotaFiscalProtocolo,
  INotaFiscalReferencias,
} from '@/models';
import { useMemo } from 'react';

// ----------------------------------------------------------------------

const exibicaoGeralDefaultValues = (currentForm?: INotaFiscalExibicaoGeral) => ({
  numero: currentForm?.numero || '',
  status: currentForm?.status.descricao || '',
  dataHoraEmissao: currentForm?.dataHoraEmissao || '',
  dataHoraSaidaEntrada: currentForm?.dataHoraSaidaEntrada || '',
});

const emitenteDefaultValues = (currentForm?: INotaFiscalEmitente) => ({
  emitenteNome: currentForm?.emitenteNome || '',
  emitenteCpfCnpj: currentForm?.emitenteCpfCnpj || '',
  emitenteTelefone: currentForm?.emitenteTelefone || '',
  emitenteInscricaoEstadual: currentForm?.emitenteInscricaoEstadual || '',
  emitenteEnderecoCep: currentForm?.emitenteEnderecoCep || '',
  emitenteEnderecoEstado: currentForm?.emitenteEnderecoEstado?.cod ?? '',
  emitenteEnderecoCidadeIbge: currentForm?.emitenteEnderecoCidadeIbge ?? '',
  emitenteEnderecoCidade: currentForm?.emitenteEnderecoCidade || '',
  emitenteEnderecoLogradouro: currentForm?.emitenteEnderecoLogradouro || '',
  emitenteEnderecoBairro: currentForm?.emitenteEnderecoBairro || '',
  emitenteEnderecoNumero: currentForm?.emitenteEnderecoNumero || '',
  emitenteEnderecoComplemento: currentForm?.emitenteEnderecoComplemento || '',
  emitenteCodigoPais: currentForm?.emitenteCodigoPais ?? '',
  emitenteNomePais: currentForm?.emitenteNomePais || '',
});

const destinatarioDefaultValues = (currentForm?: INotaFiscalDestinatario) => ({
  destinatarioNome: currentForm?.destinatarioNome || '',
  destinatarioCpfCnpj: currentForm?.destinatarioCpfCnpj || '',
  destinatarioTelefone: currentForm?.destinatarioTelefone || '',
  destinatarioEmail: currentForm?.destinatarioEmail || '',
  destinatarioInscricaoEstadual: currentForm?.destinatarioInscricaoEstadual || '',
  presencaComprador: currentForm?.presencaComprador?.cod ?? '',
  indicadorIeDestinatario: currentForm?.indicadorIeDestinatario?.cod ?? '',
  consumidorFinal: currentForm?.consumidorFinal ?? false,
  destinatarioEnderecoCep: currentForm?.destinatarioEnderecoCep || '',
  destinatarioEnderecoEstado: currentForm?.destinatarioEnderecoEstado?.cod ?? '',
  destinatarioEnderecoCidadeIbge: currentForm?.destinatarioEnderecoCidadeIbge ?? '',
  destinatarioEnderecoCidade: currentForm?.destinatarioEnderecoCidade || '',
  destinatarioEnderecoLogradouro: currentForm?.destinatarioEnderecoLogradouro || '',
  destinatarioEnderecoBairro: currentForm?.destinatarioEnderecoBairro || '',
  destinatarioEnderecoNumero: currentForm?.destinatarioEnderecoNumero || '',
  destinatarioEnderecoComplemento: currentForm?.destinatarioEnderecoComplemento || '',
});

const processoDefaultValues = (currentForm?: INotaFiscalProcesso) => ({
  naturezaOperacao: currentForm?.naturezaOperacao?.cod ?? '',
  tipoMovimento: currentForm?.tipoMovimento?.cod ?? '',
  modeloDocumentoFiscal: currentForm?.modeloDocumentoFiscal?.cod ?? '',
  formatoDanfe: currentForm?.formatoDanfe?.cod ?? '',
  tipoEmissao: currentForm?.tipoEmissao?.cod ?? '',
  identificadorDestino: currentForm?.identificadorDestino?.cod ?? '',
  finalidadeNfe: currentForm?.finalidadeNfe?.cod ?? '',
  valorTotalBaseCalculoIcms: currentForm?.valorTotalBaseCalculoIcms ?? 0,
  valorTotalIcms: currentForm?.valorTotalIcms ?? 0,
  valorTotalMercadorias: currentForm?.valorTotalMercadorias ?? 0,
  valorTotalFrete: currentForm?.valorTotalFrete ?? 0,
  valorTotalSeguro: currentForm?.valorTotalSeguro ?? 0,
  valorTotalOutrasDespesas: currentForm?.valorTotalOutrasDespesas ?? 0,
  valorTotalDesconto: currentForm?.valorTotalDesconto ?? 0,
  valorTotalNota: currentForm?.valorTotalNota ?? 0,
  valorTotalPis: currentForm?.valorTotalPis ?? 0,
  valorTotalCofins: currentForm?.valorTotalCofins ?? 0,
  valorTotalIpiDevolvido: currentForm?.valorTotalIpiDevolvido ?? 0,
  valorTotalTributos: currentForm?.valorTotalTributos ?? 0,
  valorTotalBaseCalculoIbsCbs: currentForm?.valorTotalBaseCalculoIbsCbs ?? 0,
  valorTotalIbsUf: currentForm?.valorTotalIbsUf ?? 0,
  valorTotalIbsMun: currentForm?.valorTotalIbsMun ?? 0,
  valorTotalCbs: currentForm?.valorTotalCbs ?? 0,
  linha1: currentForm?.linha1 || '',
});

const mercadoriasDefaultValues = (currentForm?: INotaFiscalMercadorias) => ({
  itens: (currentForm?.itens || []).map((item: any) => ({
    id: item.id || '',
    descricao: item.descricao || '',
    unidadeMedida: item.unidadeMedida?.cod ?? item.unidadeMedida ?? '',
    ncm: item.ncm || '',
    codigoBarras: item.codigoBarras || '',
    cest: item.cest || '',
    codigoBeneficioFiscal: item.codigoBeneficioFiscal || '',
    cfopSaida: item.cfopSaida || '',
    cfopEntrada: item.cfopEntrada || '',
    informacaoAdicional: item.informacaoAdicional || '',
    porcentagemBaseCalculoIcms: item.porcentagemBaseCalculoIcms ?? 0,
    valorBaseCalculoIcms: item.valorBaseCalculoIcms ?? 0,
    modalidadeBc: item.modalidadeBc || '',
    calculoAutomaticoIcms: item.calculoAutomaticoIcms ?? true,
    icmsCstCsosn: item.icmsCstCsosn || '',
    valorBaseCalculoStRet: item.valorBaseCalculoStRet ?? 0,
    aliquotaSt: item.aliquotaSt ?? 0,
    valorIcmsStRetido: item.valorIcmsStRetido ?? 0,
    valorIcmsProprioSubstituto: item.valorIcmsProprioSubstituto ?? 0,
    calculoAutomaticoPis: item.calculoAutomaticoPis ?? true,
    pisCst: item.pisCst || '',
    valorBaseCalculoPis: item.valorBaseCalculoPis ?? 0,
    aliquotaPis: item.aliquotaPis ?? 0,
    valorPis: item.valorPis ?? 0,
    calculoAutomaticoCofins: item.calculoAutomaticoCofins ?? true,
    cofinsCst: item.cofinsCst || '',
    valorBaseCalculoCofins: item.valorBaseCalculoCofins ?? 0,
    aliquotaCofins: item.aliquotaCofins ?? 0,
    valorCofins: item.valorCofins ?? 0,
    calculoAutomaticoIbsCbs: item.calculoAutomaticoIbsCbs ?? true,
    ibsCbsCst: item.ibsCbsCst || '',
    codigoClassTrib: item.codigoClassTrib || '',
    porcentagemBaseCalculoIbsCbs: item.porcentagemBaseCalculoIbsCbs ?? 0,
    valorBaseCalculoIbsCbs: item.valorBaseCalculoIbsCbs ?? 0,
    aliquotaIbsUf: item.aliquotaIbsUf ?? 0,
    aliquotaIbsMun: item.aliquotaIbsMun ?? 0,
    aliquotaCbs: item.aliquotaCbs ?? 0,
    valorCbs: item.valorCbs ?? 0,
    valorIbsUf: item.valorIbsUf ?? 0,
    valorIbsMun: item.valorIbsMun ?? 0,
    devolverIpi: item.devolverIpi ?? false,
    porcentagemIpiDevolvido: item.porcentagemIpiDevolvido ?? 0,
    valorIpiDevolvido: item.valorIpiDevolvido ?? 0,
    informacaoIpiDevolvido: item.informacaoIpiDevolvido || '',
    valorDesconto: item.valorDesconto ?? 0,
    valorSeguro: item.valorSeguro ?? 0,
    valorFrete: item.valorFrete ?? 0,
    valorOutras: item.valorOutras ?? 0,
    ipiCst: item.ipiCst || '',
    quantidade: item.quantidade ?? 0,
    valorUnitario: item.valorUnitario ?? 0,
    valorTotal: item.valorTotal ?? 0,
    valorSaida: item.valorSaida ?? 0,
    aliquotaIcms: item.aliquotaIcms ?? 0,
    modalidadeBcSt: item.modalidadeBcSt || '',
    origemMercadoria: item.origemMercadoria || '',
    valorIcms: item.valorIcms ?? 0,
    deletar: item.deletar ?? false,
    regraTributaria: item.regraTributaria || '',
    operacao: item.operacao || '',
    valorEntrada: item.valorEntrada || '',
  })),
});

const logisticaDefaultValues = (currentForm?: INotaFiscalLogistica) => ({
  modalidadeFrete: currentForm?.modalidadeFrete?.cod ?? '',
  transportadorNome: currentForm?.transportadorNome || '',
  transportadorCpfCnpj: currentForm?.transportadorCpfCnpj || '',
  transportadorEnderecoCompleto: currentForm?.transportadorEnderecoCompleto || '',
  transportadorEstado: currentForm?.transportadorEstado?.cod ?? '',
  transportadorCidadeIbge: currentForm?.transportadorCidadeIbge ?? '',
  transportadorCidade: currentForm?.transportadorCidade || '',
  transportadorInscricaoEstadual: currentForm?.transportadorInscricaoEstadual || '',
  volumeQuantidade: currentForm?.volumeQuantidade ?? '',
  volumeEspecie: currentForm?.volumeEspecie || '',
  volumeMarca: currentForm?.volumeMarca || '',
  volumeNumero: currentForm?.volumeNumero || '',
  volumePesoBruto: currentForm?.volumePesoBruto ?? '',
  volumePesoLiquido: currentForm?.volumePesoLiquido ?? '',
  entregaMesmoEnderecoDestinatario: currentForm?.entregaMesmoEnderecoDestinatario || false,
  entregaEnderecoCep: currentForm?.entregaEnderecoCep || '',
  entregaEnderecoEstado: currentForm?.entregaEnderecoEstado?.cod ?? '',
  entregaEnderecoCidadeIbge: currentForm?.entregaEnderecoCidadeIbge ?? '',
  entregaEnderecoCidade: currentForm?.entregaEnderecoCidade || '',
  entregaEnderecoLogradouro: currentForm?.entregaEnderecoLogradouro || '',
  entregaEnderecoBairro: currentForm?.entregaEnderecoBairro || '',
  entregaEnderecoNumero: currentForm?.entregaEnderecoNumero || '',
  entregaEnderecoComplemento: currentForm?.entregaEnderecoComplemento || '',
  entregaNome: currentForm?.entregaNome || '',
  entregaCpfCnpj: currentForm?.entregaCpfCnpj || '',
  entregaEmail: currentForm?.entregaEmail || '',
  entregaTelefone: currentForm?.entregaTelefone || '',
  entregaInscricaoEstadual: currentForm?.entregaInscricaoEstadual || '',
});

const referenciasDefaultValues = (currentForm?: INotaFiscalReferencias) => ({
  chaveAcessoReferenciada: currentForm?.chaveAcessoReferenciada || [],
});

const pagamentosDefaultValues = (currentForm?: INotaFiscalPagamentos) => ({
  pagamentos: currentForm?.pagamentos || [],
});

const protocoloDefaultValues = (currentForm?: INotaFiscalProtocolo) => ({
  codigo: currentForm?.codigo || '',
  protocolo: currentForm?.protocolo || '',
  protocoloDataHora: currentForm?.protocoloDataHora || '',
  chaveAcesso: currentForm?.chaveAcesso || '',
  chaveAcessoAdicional: currentForm?.chaveAcessoAdicional || '',
  contingencia: currentForm?.contingencia ? 'sim' : 'não',
  justificativaContingencia: currentForm?.justificativaContingencia || '',
  envios: currentForm?.envios || [],
});

export const notaFiscalDefaultValues = (currentForm?: INotaFiscalCreateUpdate) => {
  return useMemo(() => {
    return {
      id: currentForm?.id || '',
      ...exibicaoGeralDefaultValues(currentForm),
      ...emitenteDefaultValues(currentForm),
      ...destinatarioDefaultValues(currentForm),
      ...processoDefaultValues(currentForm),
      ...mercadoriasDefaultValues(currentForm),
      ...logisticaDefaultValues(currentForm),
      ...referenciasDefaultValues(currentForm),
      ...pagamentosDefaultValues(currentForm),
      ...protocoloDefaultValues(currentForm),
    };
  }, [currentForm]);
};
