up:
	docker compose up --build -d;

logs:
	docker compose logs -f;

down:
	docker compose down;

stop:
	docker compose down -v;

shell:
	docker compose exec -it central-de-vagas-reporter-service bash;